fix: fix query parsing
arenadata/kafka-tarantool-loader pull request #59
Opened 2021-08-31 07:34 UTC by YuriyVodyasov

2021-09-06 10:50 UTC, VifleY requested changes
В commit message стоит в двух словах описать из-за чего возникала ошибка и как её пофиксили

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +local function queryComplexInsert(query, params)
1) `complexInsertQuery` - так грамотнее с точки зрения английского  
2) Мне, в целом, не нравится название `queryXXX` - такое ощущение, что это должно вернуть функцию запроса или строку запроса. На самом деле, эта функция просто выполняет запрос - так давай оставим просто `complexInsert`, либо добавить `executeXXX`

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +    log.info("INFO: complex insert")
Это не стоит писать в лог  
Если хочется оставить, то нужно:  
1) Уровень логгирования - дебаг  
2) Добавить дополнительную информацию в лог - например, сам запрос

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +        log.info("INFO: Storage for ddl execution " .. cand)
Тоже убрать в `log.debug`

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +local function querySimpleInsert(query, params)
См. коммент про `queryComplexInsert`

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +    log.info("INFO: simple insert")
дебаг

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +local function qyerySelect(query, params)
`qyery` -> `query` + см. выше про наименование

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +local function queryCreateAlterDropTruncate(query, params)
см. выше про наименование  
Можно либо разбить на несколько функций как предлагал Игорь, либо назвать `executeDDL`

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +        log.info("INFO: Storage for ddl execution " .. cand)
дебаг

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +    if insertPosition == 1 and selectPosition ~= nil and fromPosition ~= nil then -- insert into... select...
`insertPosition == 1 and selectPosition ~= nil and fromPosition ~= nil` -> вот это стоит вынести в отдельный boolean, назвать его `shouldExecuteSimpleInsert` (или короче с похожим смыслом) и в комментах объяснить, почему такая комбинация условий значит простую вставку

2021-09-06 10:50 UTC, VifleY commented on app/roles/adg_api.lua
> +    local insertPosition, _ = string.find(lower_query, "insert")
По идее, сначала проверять одно условие (например, не простой ли это select запрос) и только при несовпадении начинать выполнять другие `string.find` и т.д.

2021-09-06 10:50 UTC, VifleY commented on app/utils/api_timeout_config.lua
> +    get_query_select_timeout = function(self)
Хорошо, но лучше отдельным коммитом

2021-09-06 10:50 UTC, VifleY commented on test/integration/app/roles/api_test.lua
> +    local _, _ = net_box:call("query", { [[CREATE TABLE TABLE_NAME_STAGING
Нужно вставить данные и проверить, что мы их нормально вытащили

2021-09-08 10:23 UTC, kuznetsovin reviewed
Оставил комментарии

2021-09-08 10:23 UTC, kuznetsovin commented on app/roles/adg_api.lua
> +        insertPosition, err = string.find(lower_query, "insert")
А нет ли тут смысла для типов запросов использовать функцию startswith вместо find? ведь тип запроса находится в самом начале строки

2021-09-08 10:23 UTC, kuznetsovin commented on app/roles/adg_api.lua
> +    local selectPosition = 0
Переменные лучше объявлять по мере их использования, для меньшей области видимости и читаемости

2021-09-08 10:23 UTC, kuznetsovin commented on test/integration/app/roles/api_test.lua
> +g.test_insert_select_query = function()
Для этого теста лучше завести отдельную группу

2021-09-08 10:23 UTC, kuznetsovin commented on test/integration/app/roles/api_test.lua
> +    s = box.schema.space.create('user1');
зачем тут последовательность команд все кроме индекса можно поместить в один запрос. Насчет индекса не уверен, но вроде тоже можно.

а вообще есть функция создания спейсов в приложении adg

2021-09-08 10:23 UTC, kuznetsovin commented on test/integration/app/roles/api_test.lua
> +    local _, err = storage.net_box:eval([[
аналогично замечанию выше

2021-09-14 06:38 UTC, kuznetsovin commented on app/roles/adg_api.lua
> +    else
А зачем тут else?

2021-09-14 06:38 UTC, kuznetsovin commented on app/roles/adg_api.lua
>      else
тоже самое что и выше

2021-09-14 06:39 UTC, kuznetsovin commented on test/integration/app/roles/api_test.lua
> +--local func_call= require("app.handlers.ddl_handler")
если не используются нужно убрать

2021-09-14 06:41 UTC, kuznetsovin commented on test/integration/app/roles/api_test.lua
> +              s:create_index('primary', {
что за странная конструкция

2021-09-15 08:32 UTC, merged