Picodata 44 bucket id fix
arenadata/kafka-tarantool-loader pull request #64
Opened 2021-09-29 10:31 UTC by YuriyVodyasov

Find the cause of the error and fix it

fix: add function to invalidate cache by space name

2021-09-29 13:50 UTC, VifleY requested changes

2021-09-29 13:50 UTC, VifleY commented on app/roles/adg_input_processor.lua
> +        schema_utils.cache_space(space_name)
кажется, здесь опечатка - из `sql_utils` экспортируется `remove_spaces_from_cache`

2021-09-29 13:50 UTC, VifleY commented on app/roles/adg_api.lua
> +        "app.roles.adg_input_processor",
нужно чистить не только на `adg_input_processor`, но и на стораджах

2021-09-29 13:50 UTC, VifleY commented on app/roles/adg_api.lua
> +    cartridge.rpc_call(
нужно обрабатывать ошибки

2021-09-30 07:06 UTC, kuznetsovin commented on test/integration/app/roles/api_test.lua
> +    local producer, err2 = tnt_kafka.Producer.create({ brokers = "localhost:9092" })
надо поменять на kafka:29092 чтобы тест на ci прошел

2021-09-30 07:31 UTC, VifleY commented on app/roles/adg_api.lua
> +    cartridge.rpc_call(
Замечание по обработке всех ошибок всё еще актуально

2021-09-30 07:31 UTC, VifleY commented on app/roles/adg_api.lua
> +            conn:call(
см. выше

2021-09-30 07:31 UTC, VifleY commented on app/utils/schema_utils.lua
> +local function clean_cache_by_space(space_name)
из названия неясно, что это именно кэш `bucket_id_fields`

2021-10-05 13:32 UTC, merged